# Generated by Django 4.1.7 on 2023-07-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dlink',
            field=models.URLField(default='https://www.wikipedia.org/'),
            preserve_default=False,
        ),
    ]
