# Generated by Django 4.1.7 on 2023-07-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0002_department_dlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('departmentname',), 'verbose_name': 'district', 'verbose_name_plural': 'districts'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('empname',), 'verbose_name': 'branch', 'verbose_name_plural': 'branches'},
        ),
    ]
